#!/usr/bin/env python3
import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

from ahc_hub_manifest import resolve_hub_addons_json


REQUIRED_STRING_FIELDS = ("name", "author", "category", "folder", "repo", "description")
OPTIONAL_STRING_FIELDS = ("source_subdir", "avatar_url", "version", "source", "page_url")


class ManifestError(Exception):
    pass


def c_string(value: str | None) -> str:
    if value is None:
        return "NULL"
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def c_ident(prefix: str, index: int) -> str:
    return f"{prefix}_{index:04d}"


def require_string(addon: dict[str, Any], field: str, index: int) -> str:
    value = addon.get(field)
    if not isinstance(value, str) or not value.strip():
        raise ManifestError(f"addon[{index}] missing non-empty string field: {field}")
    return value


def optional_string(addon: dict[str, Any], field: str) -> str | None:
    value = addon.get(field)
    return value if isinstance(value, str) and value else None


def addon_categories(addon: dict[str, Any], index: int) -> list[str]:
    category = require_string(addon, "category", index)
    raw = addon.get("categories")
    if raw is None:
        return [category]
    if not isinstance(raw, list) or not raw:
        raise ManifestError(f"addon[{index}] categories must be a non-empty string array")
    categories: list[str] = []
    for item in raw:
        if not isinstance(item, str) or not item.strip():
            raise ManifestError(f"addon[{index}] categories contains an invalid value")
        if item not in categories:
            categories.append(item)
    if categories[0] != category:
        raise ManifestError(f"addon[{index}] category must match categories[0]")
    return categories


def validate_manifest(data: dict[str, Any]) -> list[dict[str, Any]]:
    addons = data.get("addons")
    if not isinstance(addons, list) or not addons:
        raise ManifestError("manifest must contain a non-empty addons array")

    seen_ids: set[str] = set()
    for index, addon in enumerate(addons):
        if not isinstance(addon, dict):
            raise ManifestError(f"addon[{index}] must be an object")
        addon_id = addon.get("id")
        if not isinstance(addon_id, str) or not addon_id.strip():
            raise ManifestError(f"addon[{index}] missing non-empty string field: id")
        if addon_id in seen_ids:
            raise ManifestError(f"duplicate addon id: {addon_id}")
        seen_ids.add(addon_id)

        for field in REQUIRED_STRING_FIELDS:
            require_string(addon, field, index)
        for field in OPTIONAL_STRING_FIELDS:
            value = addon.get(field)
            if value is not None and not isinstance(value, str):
                raise ManifestError(f"addon[{index}] optional field {field} must be a string")
        addon_categories(addon, index)
        repo = addon["repo"]
        if not re.match(r"^(https?://|git@)", repo):
            raise ManifestError(f"addon[{index}] repo must be an http(s) URL or git SSH URL")

    return addons


def generate_c(addons: list[dict[str, Any]]) -> str:
    lines: list[str] = [
        "/* Generated by scripts/generate_addon_catalog.py. Do not edit. */",
        '#include "addons/addon_catalog.h"',
        "",
    ]

    for index, addon in enumerate(addons):
        categories = addon_categories(addon, index)
        ident = c_ident("AHC_ADDON_CATEGORIES", index)
        lines.append(f"static const char *{ident}[] = {{")
        for category in categories:
            lines.append(f"    {c_string(category)},")
        lines.append("};")
        lines.append("")

    lines.append("static const AhcAddon AHC_ADDONS[] = {")
    for index, addon in enumerate(addons):
        categories_ident = c_ident("AHC_ADDON_CATEGORIES", index)
        fields = [
            require_string(addon, "id", index),
            require_string(addon, "name", index),
            require_string(addon, "author", index),
            require_string(addon, "category", index),
            require_string(addon, "folder", index),
            require_string(addon, "repo", index),
            require_string(addon, "description", index),
            optional_string(addon, "source_subdir"),
            optional_string(addon, "avatar_url"),
            optional_string(addon, "version"),
            optional_string(addon, "source"),
            optional_string(addon, "page_url"),
        ]
        rendered = ", ".join(c_string(value) for value in fields)
        category_count = len(addon_categories(addon, index))
        lines.append(f"    {{ {rendered}, {categories_ident}, {category_count}u }},")
    lines.append("};")
    lines.append("")
    lines.append("const AhcAddon *ahc_addon_catalog_items(void)")
    lines.append("{")
    lines.append("    return AHC_ADDONS;")
    lines.append("}")
    lines.append("")
    lines.append("size_t ahc_addon_catalog_count(void)")
    lines.append("{")
    lines.append("    return sizeof(AHC_ADDONS) / sizeof(AHC_ADDONS[0]);")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate and generate the baked addon catalog.")
    parser.add_argument(
        "--input",
        type=Path,
        default=None,
        help="Path to manifest JSON (default: synastria-monorepo-addons hub, same as CMake).",
    )
    parser.add_argument("--output", help="Path to generated C output.")
    parser.add_argument("--check", action="store_true", help="Validate only; do not write generated output.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    companion_root = Path(__file__).resolve().parents[1]
    try:
        manifest_path = args.input if args.input is not None else resolve_hub_addons_json(companion_root)
    except FileNotFoundError as exc:
        print(f"generate_addon_catalog.py: {exc}", file=sys.stderr)
        return 1
    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise ManifestError("manifest root must be an object")
        addons = validate_manifest(data)
        if args.check:
            print(f"Validated {len(addons)} addons from {manifest_path}")
            return 0
        if not args.output:
            raise ManifestError("--output is required unless --check is used")
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(generate_c(addons), encoding="utf-8", newline="\n")
        print(f"Generated {len(addons)} baked addons at {output_path}")
        return 0
    except (OSError, json.JSONDecodeError, ManifestError) as exc:
        print(f"generate_addon_catalog.py: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
